# Generated by Django 4.2.5 on 2023-10-22 19:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('detalle', models.CharField(max_length=1000, null=True)),
                ('detalle_corto', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('S', 'Suspención de actividades'), ('C', 'Suspención de clase'), ('I', 'Informaciones')], default='I', max_length=2)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_ultima_modificacion', models.DateTimeField(default=datetime.datetime.now)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidad')),
            ],
        ),
    ]
